name: TokensPlugin
main: net.timme7893.tokens.Tokens
description: A tokens generator plugin with supported economy.
version: 0.1
author: [Timme7893]

commands:
  tokens:
    description: A command for the Tokens economy.